In [1]:
import collections

In [4]:
od = collections.OrderedDict()

In [5]:
od['a2'] = 1

In [6]:
od['a1'] = 2

In [8]:
od.keys()

['a2', 'a1']

In [10]:
od['a3'] = 3

In [11]:
od['a3'] += 3

In [12]:
od

OrderedDict([('a2', 1), ('a1', 2), ('a3', 6)])

In [14]:
items = od.iterkeys()

In [17]:
items

[('a2', 1), ('a1', 2), ('a3', 6)]

In [21]:
s = ""
for k in od.iterkeys():
    s += k
    s += " "
    s += str(od[k])
    s += "\n"
print s

a2 1
a1 2
a3 6



In [22]:
import numpy as np

In [24]:
q = np.array([1,2,3])

In [25]:
q

array([1, 2, 3])

In [26]:
w = np.array([1,2,3],float)

In [27]:
w

array([ 1.,  2.,  3.])

In [29]:
np.float(15)

15.0

In [31]:
for i in list(q):
    print i

1
2
3


In [34]:
e1 = np.float(15)
e2 = np.float(3.32)
e = np.array([e1,e2],float)
e

array([ 15.  ,   3.32])

In [40]:
inp ="1.1 -1.2" #"1 2 3 4 -8 -10"
ss = inp.split(" ")
inp_list = [float(s) for s in ss]
print inp_list
n = len(inp_list)
out = np.zeros(n,dtype=np.float)
for i in range(n-1):
    out[i] = np.float(inp_list.pop())
print out

[1.1, -1.2]
[-1.2  0. ]


In [41]:
reduce(lambda x,y: x+y, range(5))

10

In [42]:
import json

In [46]:
print json.dumps(od)

{"a2": 1, "a1": 2, "a3": 6}


In [44]:
od

OrderedDict([('a2', 1), ('a1', 2), ('a3', 6)])

In [45]:
print od

OrderedDict([('a2', 1), ('a1', 2), ('a3', 6)])


In [ ]:
out = np.zeros(len(inp_list))

In [ ]:
s=""
for i in od.items():
    s += i.